-- PATCH: Ensure all relevant 'id' columns are SERIAL/BIGSERIAL or uuid DEFAULT gen_random_uuid().
-- This resolves errors with missing/NULL primary keys and allows record/bulk creation/import without specifying the ID.
-- STEP 1: Load/verify the 'pgcrypto' extension (required for gen_random_uuid()).
-- Only run CREATE EXTENSION if not already enabled.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pgcrypto') THEN
        CREATE EXTENSION pgcrypto;
    END IF;
END$$;

-- STEP 2: PATCH TABLES

-- ************ COURSES ************
-- If 'id' on courses is NOT already SERIAL, BIGSERIAL, or uuid DEFAULT gen_random_uuid(), alter as below.
-- For empty tables, you can just replace the column.
-- For tables with data: Use a two-step process (add new column, fill values, swap, and drop old if needed).

-- ==> If you want integer autoincrement ids:
-- Comment out uuid part and un-comment the SERIAL if you prefer integers
-- ALTER TABLE courses ALTER COLUMN id SET DATA TYPE integer;
-- ALTER TABLE courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ==> Recommended: Use UUID for distributed/global uniqueness
ALTER TABLE courses
    ALTER COLUMN id SET DATA TYPE uuid USING (CASE
        WHEN id IS NULL THEN gen_random_uuid() ELSE id::uuid END),
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN id SET NOT NULL;

-- To ensure primary key constraint (if not present):
-- ALTER TABLE courses ADD PRIMARY KEY (id);

-- ************ FACULTY ************
ALTER TABLE faculty
    ALTER COLUMN id SET DATA TYPE uuid USING (CASE
        WHEN id IS NULL THEN gen_random_uuid() ELSE id::uuid END),
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN id SET NOT NULL;
-- ALTER TABLE faculty ADD PRIMARY KEY (id);

-- ************ ROOMS ************
ALTER TABLE rooms
    ALTER COLUMN id SET DATA TYPE uuid USING (CASE
        WHEN id IS NULL THEN gen_random_uuid() ELSE id::uuid END),
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN id SET NOT NULL;
-- ALTER TABLE rooms ADD PRIMARY KEY (id);

-- ************ TIMETABLE_ENTRIES ************
ALTER TABLE timetable_entries
    ALTER COLUMN id SET DATA TYPE uuid USING (CASE
        WHEN id IS NULL THEN gen_random_uuid() ELSE id::uuid END),
    ALTER COLUMN id SET DEFAULT gen_random_uuid(),
    ALTER COLUMN id SET NOT NULL;
-- ALTER TABLE timetable_entries ADD PRIMARY KEY (id);

-- ************ Add any additional tables as needed (e.g., departments, allocations, etc.) ************
-- Copy the block above for each, replacing the table name.

-- INSTRUCTIONS:
-- 1. Run this file in your Supabase SQL editor or psql.
-- 2. If you encounter errors because your table already has a PRIMARY KEY or SERIAL/UUID, adjust the patch to skip or modify only the DEFAULT part.
-- 3. For tables with existing data and indexed foreign keys, consider rebuilding FKs referring to IDs if you change types.
-- 4. Ensure that your application frontend does NOT send an explicit 'id: null' field on inserts. Remove 'id' property from payload when creating new rows (frontend should omit 'id' entirely if it is auto-generated).
-- 5. Foreign keys (example): For referencing tables, ensure FK has type uuid if the main table uses uuid.

-- SAFETY:
-- Always back up your data before performing schema-altering operations!

-- RECOMMENDED: Keep all table ids as uuid with default gen_random_uuid() for best compatibility in modern distributed applications.
-- For bulk import: if importing legacy integer IDs, create import columns temporarily, then migrate.
